services:
  flush-log:
    image: cosmtrek/air
    working_dir: /src
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - GOAPP_PORT=:8080
    volumes:
      - ./pwa:/src/
  flush-api:
    build:
      context: ./api/
      dockerfile: Dockerfile-hot-reload
    working_dir: /src
    ports:
      - 6789:6789
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/?connectTimeoutMS=3000&timeoutMS=4000&socketTimeoutMS=3000&serverSelectionTimeoutMS=4000
      - MOCK_NOT_AVAILABLE=false
    volumes:
      - ./api:/src/
  mongo:
    image: mongo:8.0.1-noble
    restart: unless-stopped
