services:
  flush-log:
    image: cosmtrek/air
    working_dir: /src
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - GOAPP_PORT=:8080
    volumes:
      - ./pwa:/src/
  flush-api:
    build:
      context: ./api/
      dockerfile: Dockerfile-hot-reload
    working_dir: /src
    ports:
      - 6789:6789
    restart: unless-stopped
    environment:
      - MONGO_URL=mock
      - MOCK_NOT_AVAILABLE=false
    volumes:
      - ./api:/src/
