version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  dev:
    cmds:
      - task cleanup
      - docker volume prune -af
      - docker compose up -d --build
      - task logs
  cleanup:
    cmds:
      - docker compose down -v
  logs:
    cmds:
      - docker compose logs -f
  test-api-mock:
    cmds:
      - uv run pytest tests/test_mock.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mock
  test-api-integration:
    cmds:
      - uv run pytest tests/test_integration.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mongodb://localhost:27017
  test-api-integration-ci:
    cmds:
      - uv run pytest tests/test_integration.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mongodb://mongo:27017
  init-uv-venv:
    cmds:
      - uv venv
      - uv pip install -r requirements.txt
      - uv pip install pytest httpx
    dir: api
