version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  dev:
    cmds:
      - task cleanup
      - docker volume prune -af
      - docker compose up -d --build
      - task logs
  cleanup:
    cmds:
      - docker compose down -v
  logs:
    cmds:
      - docker compose logs -f
  test-api-unit:
    cmds:
      - uv run pytest tests/unit/ -v
    dir: api
  test-api-mock:
    cmds:
      - uv run pytest tests/test_mock.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mock
  test-api-integration:
    cmds:
      - uv run pytest tests/test_integration.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mongodb://localhost:27017
  test-api-integration-ci:
    cmds:
      - uv run pytest tests/test_integration.py -v
      - uv run pytest tests/universal/ -v
    dir: api
    env:
      MONGO_URL: mongodb://mongo:27017
  init-uv-venv:
    cmds:
      - uv venv
      - uv pip install -r requirements.txt
      - uv pip install pytest httpx
    dir: api
  test-pwa-unit:
    cmds:
      - go test -v
    dir: pwa/test/unit
  test-pwa-integration:
    cmds:
      - go mod download
      - go test -v
    dir: pwa/test/integration
    env:
      GOAPP_URL: http://localhost:8080
  test-pwa-integration-show-window:
    cmds:
      - go mod download
      - go test -v -rod=show
    dir: pwa/test/integration
    env:
      GOAPP_URL: http://localhost:8080
  test-pwa-integration-container:
    cmds:
      - docker rm -f pwatest || true
      - docker build -t pwa:test -f ./Dockerfile-test .
      - docker run --rm --net host -e GOAPP_URL=http://localhost:8080 --name pwatest pwa:test
      - docker rm -f pwatest || true
    dir: pwa/test/integration
