FROM python:3.12.6-slim-bookworm
WORKDIR /src
RUN apt-get update && apt-get install netcat-traditional -y && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
USER 1000:1000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6789", "--reload"]
